export const UNIT_LABELS: Record<string, string> = {
  PCS: 'قطعة',
  EA: 'قطعة',
  UNIT: 'وحدة',
  KG: 'كيلو جرام',
  G: 'جرام',
  TON: 'طن',
  M: 'متر',
  CM: 'سنتيمتر',
  MM: 'مليمتر',
  M2: 'متر مربع',
  SQM: 'متر مربع',
  M3: 'متر مكعب',
  CBM: 'متر مكعب',
  L: 'لتر',
  ML: 'مليلتر',
  BAG: 'شيكارة',
  BOX: 'علبة',
  CARTON: 'كرتونة',
  PACK: 'عبوة',
  SET: 'طقم',
  PAIR: 'زوج',
  ROLL: 'لفة',
  BUNDLE: 'ربطة',
  PALLET: 'طبالي',
  DRUM: 'برميل',
  SHEET: 'لوح',
  BAR: 'سيخ',
  LOT: 'دفعة',
  TRIP: 'نقلة',
  HOUR: 'ساعة',
  DAY: 'يوم',
  MONTH: 'شهر',
  SERVICE: 'خدمة',
};

const UNIT_ALIASES: Record<string, string> = {
  'M³': 'M3',
  'م3': 'M3',
  'متر مكعب': 'M3',
  'CUBIC METER': 'M3',
  'CUBIC METERS': 'M3',
  'CBM': 'M3',
  'M²': 'M2',
  'م2': 'M2',
  'متر مربع': 'M2',
  'SQM': 'M2',
  'SQUARE METER': 'M2',
  'SQUARE METERS': 'M2',
  'قطعة': 'PCS',
  'قطع': 'PCS',
  'PC': 'PCS',
  'PCS': 'PCS',
  'PIECE': 'PCS',
  'PIECES': 'PCS',
  'EA': 'PCS',
  'EACH': 'PCS',
  'NO': 'PCS',
  'NOS': 'PCS',
  'NUMBER': 'PCS',
  'ITEM': 'PCS',
  'ITEMS': 'PCS',
  'وحدة': 'UNIT',
  'وحدات': 'UNIT',
  'UNIT': 'UNIT',
  'UNITS': 'UNIT',
  'كيلو': 'KG',
  'كيلوجرام': 'KG',
  'كيلو جرام': 'KG',
  'كجم': 'KG',
  'كغ': 'KG',
  'KG': 'KG',
  'KGS': 'KG',
  'KILOGRAM': 'KG',
  'KILOGRAMS': 'KG',
  'جرام': 'G',
  'جم': 'G',
  'G': 'G',
  'GM': 'G',
  'GRAM': 'G',
  'GRAMS': 'G',
  'طن': 'TON',
  'TON': 'TON',
  'TONS': 'TON',
  'MT': 'TON',
  'متر': 'M',
  'م': 'M',
  'M': 'M',
  'MTR': 'M',
  'METER': 'M',
  'METERS': 'M',
  'سنتيمتر': 'CM',
  'سم': 'CM',
  'CM': 'CM',
  'مليمتر': 'MM',
  'مم': 'MM',
  'MM': 'MM',
  'لتر': 'L',
  'L': 'L',
  'LTR': 'L',
  'LITER': 'L',
  'LITERS': 'L',
  'مليلتر': 'ML',
  'مل': 'ML',
  'ML': 'ML',
  'شيكارة': 'BAG',
  'شكارة': 'BAG',
  'شوال': 'BAG',
  'BAG': 'BAG',
  'BAGS': 'BAG',
  'SACK': 'BAG',
  'SACKS': 'BAG',
  'علبة': 'BOX',
  'علب': 'BOX',
  'BOX': 'BOX',
  'BOXES': 'BOX',
  'كرتونة': 'CARTON',
  'كراتين': 'CARTON',
  'CARTON': 'CARTON',
  'CARTONS': 'CARTON',
  'CTN': 'CARTON',
  'عبوة': 'PACK',
  'PACK': 'PACK',
  'PACKAGE': 'PACK',
  'PACKAGES': 'PACK',
  'PKT': 'PACK',
  'طقم': 'SET',
  'SET': 'SET',
  'SETS': 'SET',
  'زوج': 'PAIR',
  'PAIR': 'PAIR',
  'PAIRS': 'PAIR',
  'لفة': 'ROLL',
  'لفات': 'ROLL',
  'ROLL': 'ROLL',
  'ROLLS': 'ROLL',
  'ربطة': 'BUNDLE',
  'BUNDLE': 'BUNDLE',
  'BUNDLES': 'BUNDLE',
  'طبالي': 'PALLET',
  'طبلية': 'PALLET',
  'PALLET': 'PALLET',
  'PALLETS': 'PALLET',
  'برميل': 'DRUM',
  'براميل': 'DRUM',
  'DRUM': 'DRUM',
  'BARREL': 'DRUM',
  'لوح': 'SHEET',
  'ألواح': 'SHEET',
  'SHEET': 'SHEET',
  'SHEETS': 'SHEET',
  'سيخ': 'BAR',
  'أسياخ': 'BAR',
  'قضيب': 'BAR',
  'BAR': 'BAR',
  'BARS': 'BAR',
  'لوط': 'LOT',
  'دفعة': 'LOT',
  'LOT': 'LOT',
  'نقلة': 'TRIP',
  'مشوار': 'TRIP',
  'رد': 'TRIP',
  'TRIP': 'TRIP',
  'ساعة': 'HOUR',
  'ساعات': 'HOUR',
  'HOUR': 'HOUR',
  'HOURS': 'HOUR',
  'HR': 'HOUR',
  'HRS': 'HOUR',
  'يوم': 'DAY',
  'أيام': 'DAY',
  'DAY': 'DAY',
  'DAYS': 'DAY',
  'شهر': 'MONTH',
  'MONTH': 'MONTH',
  'MONTHS': 'MONTH',
  'خدمة': 'SERVICE',
  'عمل': 'SERVICE',
  'SERVICE': 'SERVICE',
  'JOB': 'SERVICE',
};

const normalizeUnit = (unit?: string | null): string => {
  const trimmed = (unit || '').trim();
  if (!trimmed) return '';
  const aliasKey = UNIT_ALIASES[trimmed] || UNIT_ALIASES[trimmed.toUpperCase()];
  return (aliasKey || trimmed).toUpperCase();
};

export const getUnitLabel = (unit?: string | null): string => {
  const trimmed = (unit || '').trim();
  if (!trimmed) return '—';
  const normalized = normalizeUnit(trimmed);
  if (UNIT_LABELS[normalized]) return UNIT_LABELS[normalized];
  if (UNIT_ALIASES[trimmed] && UNIT_LABELS[UNIT_ALIASES[trimmed]]) return UNIT_LABELS[UNIT_ALIASES[trimmed]];
  if (UNIT_ALIASES[trimmed.toUpperCase()] && UNIT_LABELS[UNIT_ALIASES[trimmed.toUpperCase()]]) return UNIT_LABELS[UNIT_ALIASES[trimmed.toUpperCase()]];
  return trimmed;
};

export const getUnitValue = (unit?: string | null): string => {
  const normalized = normalizeUnit(unit);
  if (!normalized) return 'UNIT';
  if (UNIT_LABELS[normalized]) return normalized;
  const arabicEntry = Object.entries(UNIT_LABELS).find(([, label]) => label === unit?.trim());
  return arabicEntry?.[0] || normalized;
};

export const getUnitOptions = (units: string[]): Array<{ value: string; label: string }> =>
  units.map((value) => ({ value, label: getUnitLabel(value) }));
